version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run create-environment
            - run: npm run check
            - run: npm run gcp-build
            - persist_to_workspace:
                root: ~/project
                paths: .
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: gcloud app deploy
      - run: gcloud app deploy cron.yaml
workflows:
    build-lint-deploy:
      jobs:
        - build-and-lint
        - deploy:
            requires:
              - build-and-lint
            # filters:
            #   branches:
            #     only: master
